# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hamask', '0005_auto_20170529_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workout_group',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
