# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hamask', '0009_workout_exercise_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout_exercise',
            name='order',
            field=models.PositiveIntegerField(),
        ),
    ]
