# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-15 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hamask', '0010_auto_20170608_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='rep_scheme',
            field=models.CharField(blank=True, choices=[('MAX_PERCENTAGE', '% of Max'), ('RPE', 'RPE'), ('WEIGHT', 'Weight')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='workout_exercise',
            name='rep_scheme',
            field=models.CharField(choices=[('MAX_PERCENTAGE', '% of Max'), ('RPE', 'RPE'), ('WEIGHT', 'Weight')], max_length=30),
        ),
        migrations.DeleteModel(
            name='Rep_Scheme',
        ),
    ]
