# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-20 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hamask', '0012_auto_20170620_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='repeatable',
            field=models.BooleanField(default=False),
        ),
    ]
