# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-26 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hamask', '0013_program_repeatable'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout_log',
            name='status',
            field=models.CharField(choices=[('COMPL', 'Completed'), ('SKIPD', 'Skipped'), ('IN_PROGR', 'In Progress')], default='COMPL', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='program',
            name='rounding',
            field=models.CharField(choices=[('NO', 'No rounding'), ('0.5', '0.5'), ('5', '5'), ('10', '10'), ('LAST_5', 'Last digit is 5')], default='NO', max_length=30),
        ),
        migrations.AlterField(
            model_name='workout_exercise_log',
            name='weight',
            field=models.FloatField(blank=True),
        ),
    ]
