# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-29 20:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hamask', '0014_auto_20170626_1706'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workout_exercise_log',
            old_name='Workout_Exercise',
            new_name='workout_exercise',
        ),
        migrations.RenameField(
            model_name='workout_exercise_log',
            old_name='Workout_Log',
            new_name='workout_log',
        ),
    ]
