# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-06 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hamask', '0015_auto_20170629_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout_exercise_log',
            name='order',
            field=models.PositiveIntegerField(default='1'),
            preserve_default=False,
        ),
    ]
