# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-06 19:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hamask', '0017_auto_20170706_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout_exercise_log',
            name='exercise',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, to='hamask.Exercise'),
            preserve_default=False,
        ),
    ]
