# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-31 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hamask', '0018_workout_exercise_log_exercise'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='category',
            field=models.CharField(blank=True, choices=[('MAIN', 'Main Lifts'), ('MAIN_VARTN', 'Main Lift Variation'), ('COMPN_ACESR', 'Compound Accessory'), ('STRON', 'Strongman'), ('ISOLT_ACESR', 'Isolation')], max_length=30, null=True),
        ),
    ]
