# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-01 19:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hamask', '0019_exercise_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout_log',
            name='lifter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hamask.Lifter'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='category',
            field=models.CharField(blank=True, choices=[('MAIN', 'Main Lift'), ('MAIN_VARTN', 'Main Lift Variation'), ('COMPN_ACESR', 'Compound Accessory'), ('STRON', 'Strongman'), ('ISOLT_ACESR', 'Isolation')], max_length=30, null=True),
        ),
    ]
