# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-02 20:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hamask', '0020_auto_20170801_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout_log',
            name='status',
            field=models.CharField(choices=[('COMPL', 'Completed'), ('SKIPD', 'Skipped')], max_length=30),
        ),
        migrations.AlterField(
            model_name='workout_log',
            name='workout_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
