# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-16 19:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hamask', '0021_auto_20170802_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lifter_Weight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField()),
                ('weight', models.FloatField()),
                ('lifter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hamask.Lifter')),
            ],
        ),
    ]
