# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-28 01:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hamask', '0023_auto_20171126_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='is_current',
        ),
        migrations.AddField(
            model_name='program',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
