# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-05 01:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hamask', '0024_auto_20171127_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='training_max_percentage',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
