# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-16 21:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hamask', '0025_program_training_max_percentage'),
    ]
