# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-16 21:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hamask', '0026_auto_20171216_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='program',
            name='start_date',
        ),
    ]
