# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-16 21:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hamask', '0026_auto_20171216_1529'),
        ('hamask', '0027_auto_20171216_1614'),
    ]

    operations = [
    ]
