# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-23 23:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hamask', '0028_merge_20171216_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
