# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-28 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hamask', '0029_auto_20171223_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout_exercise',
            name='percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workout_exercise_log',
            name='percentage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
