# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-06 00:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hamask', '0030_auto_20171228_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meet_Planner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bodyweight', models.FloatField(blank=True, null=True)),
                ('squat_1', models.FloatField(blank=True, null=True)),
                ('squat_2', models.FloatField(blank=True, null=True)),
                ('squat_3', models.FloatField(blank=True, null=True)),
                ('bench_1', models.FloatField(blank=True, null=True)),
                ('bench_2', models.FloatField(blank=True, null=True)),
                ('bench_3', models.FloatField(blank=True, null=True)),
                ('deadlift_1', models.FloatField(blank=True, null=True)),
                ('deadlift_2', models.FloatField(blank=True, null=True)),
                ('deadlift_3', models.FloatField(blank=True, null=True)),
                ('lifter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hamask.Lifter')),
            ],
        ),
        migrations.AlterField(
            model_name='lifter_stats',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
